apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotion-viva-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emotion-viva-backend
  template:
    metadata:
      labels:
        app: emotion-viva-backend
    spec:
      containers:
        - name: emotion-viva-backend
          image: <your_docker_image>
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: emotion-viva-backend
spec:
  selector:
    app: emotion-viva-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
