version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - REDIS_HOST=redis
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      - mysql
      - redis
      - rabbitmq

  scraper:
    build:
      context: .
      dockerfile: apps/scraper/Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/scraper
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
