version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file: apps/api/.env.docker
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - app-network

  scraper:
    build:
      context: .
      dockerfile: apps/scraper/Dockerfile
    env_file: apps/scraper/.env.docker
    deploy:
      replicas: 2
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    env_file: .env.prod
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  mysql_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:
