version: '3.8'

services:
  backend:
    build: .
    container_name: emotion_viva_backend
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    container_name: emotion_viva_redis
    ports:
      - '6379:6379'

  rabbitmq:
    image: 'rabbitmq:management'
    container_name: emotion_viva_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672' # RabbitMQ management UI
